#!/bin/bash

echo "📧 Manual Testing Guide for Leafnote Analytics"
echo "=============================================="
echo ""
echo "Since Supabase CLI installation requires system updates,"
echo "here's how to test and deploy manually:"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "OPTION 1: Use Supabase Dashboard (No CLI needed)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Apply Database Migration:"
echo "   - Go to: https://supabase.com/dashboard/project/YOUR_PROJECT/sql"
echo "   - Copy contents of: supabase/migrations/2025_12_13_create_leafnote_events_table.sql"
echo "   - Paste and run in SQL Editor"
echo ""
echo "2. Deploy Edge Function:"
echo "   - Go to: https://supabase.com/dashboard/project/YOUR_PROJECT/functions"
echo "   - Click 'Create a new function'"
echo "   - Name: weekly-report"
echo "   - Copy contents of: supabase/functions/weekly-report/index.ts"
echo "   - Paste and deploy"
echo ""
echo "3. Set Function Secrets:"
echo "   - Go to: https://supabase.com/dashboard/project/YOUR_PROJECT/settings/functions"
echo "   - Add these secrets:"
echo "     * RESEND_API_KEY=your_resend_key"
echo "     * REPORT_TO_EMAIL=smita.kulkarni89@gmail.com"
echo "     * REPORT_SECRET=your_random_secret (generate with: openssl rand -base64 32)"
echo ""
echo "4. Test the Function:"
echo "   - Copy your function URL from the dashboard"
echo "   - Run this command:"
echo ""
echo "   curl -X POST 'https://YOUR_PROJECT_REF.supabase.co/functions/v1/weekly-report' \\"
echo "     -H 'x-report-secret: YOUR_SECRET'"
echo ""
echo "   - Check smita.kulkarni89@gmail.com for the email!"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "OPTION 2: Install Supabase CLI (requires system update first)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Update Command Line Tools:"
echo "   sudo rm -rf /Library/Developer/CommandLineTools"
echo "   sudo xcode-select --install"
echo ""
echo "2. Install Supabase CLI:"
echo "   brew install supabase/tap/supabase"
echo ""
echo "3. Then run:"
echo "   ./deploy-analytics.sh"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🎯 Recommended: Use Option 1 (Dashboard) - it's faster!"
echo ""
echo "Need your Resend API key? Get it from: https://resend.com/api-keys"
echo ""
