#!/bin/bash

echo "📋 Leafnote Analytics - Simple Setup Guide"
echo "=========================================="
echo ""

# Generate secret
REPORT_SECRET=$(openssl rand -base64 32)

echo "Step 1: Apply Database Migration"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Go to: https://supabase.com/dashboard/project/ipeihablpncfzgkwvdhi/sql"
echo ""
echo "Copy and paste this SQL, then click RUN:"
echo ""
cat supabase/migrations/2025_12_13_create_leafnote_events_table.sql
echo ""
echo ""
read -p "✓ Done? Press ENTER to continue..."
echo ""

echo "Step 2: Deploy Edge Function"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Go to: https://supabase.com/dashboard/project/ipeihablpncfzgkwvdhi/functions"
echo ""
echo "Click 'Create a new function'"
echo "Name: weekly-report"
echo ""
echo "Then open this file in a new window:"
echo "  ${PWD}/supabase/functions/weekly-report/index.ts"
echo ""
echo "Copy ALL the code and paste into the function editor, then Deploy"
echo ""
read -p "✓ Deployed? Press ENTER to continue..."
echo ""

echo "Step 3: Set Function Secrets"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Go to: https://supabase.com/dashboard/project/ipeihablpncfzgkwvdhi/settings/functions"
echo ""
echo "Add these THREE secrets (click 'Add secret' for each):"
echo ""
echo "Name: RESEND_API_KEY"
echo "Value: re_j5UYc3Jb_EQQ3eGCWJ2C3AoCrEPEzP1Lk"
echo ""
echo "Name: REPORT_TO_EMAIL"
echo "Value: smita.kulkarni89@gmail.com"
echo ""
echo "Name: REPORT_SECRET"
echo "Value: ${REPORT_SECRET}"
echo ""
read -p "✓ All secrets added? Press ENTER to test email..."
echo ""

echo "Step 4: Testing Email Delivery..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""

RESPONSE=$(curl -s -X POST "https://ipeihablpncfzgkwvdhi.supabase.co/functions/v1/weekly-report" \
  -H "x-report-secret: ${REPORT_SECRET}" \
  -H "Content-Type: application/json")

echo "$RESPONSE" | jq . 2>/dev/null || echo "$RESPONSE"
echo ""

if echo "$RESPONSE" | grep -q '"ok":true'; then
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo "✅ SUCCESS! Email sent!"
  echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
  echo ""
  echo "📧 Check: smita.kulkarni89@gmail.com"
  echo "   (Include spam folder)"
  echo ""
else
  echo "❌ Issue detected. Response above may show the error."
  echo "Common fixes:"
  echo "  - Verify all 3 secrets are set correctly"
  echo "  - Check Resend API key is valid"
  echo "  - Wait 30 seconds and try again (function may be deploying)"
  echo ""
  echo "Retry test with:"
  echo "curl -X POST 'https://ipeihablpncfzgkwvdhi.supabase.co/functions/v1/weekly-report' \\"
  echo "  -H 'x-report-secret: ${REPORT_SECRET}'"
fi

echo ""
echo "Step 5: Configure GitHub Actions (For Weekly Automation)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "1. Go to your GitHub repo → Settings → Secrets and variables → Actions"
echo ""
echo "2. Click 'New repository secret' and add:"
echo ""
echo "   Name: SUPABASE_FUNCTION_URL"
echo "   Secret: https://ipeihablpncfzgkwvdhi.supabase.co/functions/v1"
echo ""
echo "3. Click 'New repository secret' again and add:"
echo ""
echo "   Name: REPORT_SECRET"
echo "   Secret: ${REPORT_SECRET}"
echo ""
echo "4. Commit and push your code to activate the workflow"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "🎉 Setup Complete!"
echo ""
echo "📅 Weekly reports will arrive every Friday at 9 AM UTC"
echo ""
echo "💾 Save this for future testing:"
echo "   REPORT_SECRET: ${REPORT_SECRET}"
echo ""
